project: RL_NEW_MOLECULE_DESIGN
entity: whizz
id: deltaQED_run.0
hyperparameters:
  training:
    gamma: 0.99              # Discount factor
    tau: 0.005               # Soft update rate
    batch_size: 32          # Minibatch size for training
    capacity: 500000        # Max size for replay buffer
    start_timesteps: 3000   # Number of timesteps before training
    max_timesteps: 500000       # Number of timesteps
    max_steps: 5             # Max steps per episode
    policy_freq: 2           # Frequency of policy updates
    seed: 42                 # Random seed
    eval_freq: 10e3          # Frequency of evaluation
    save_freq: 5e3         # Frequency of model saving
  optimizers:
    actor_lr: 1e-4           # Learning rate for actor networks
    critic_lr: 3e-4          # Learning rate for critic networks
  temperature:
    initial_temperature: 1.0 # Initial temperature parameter for Gumbel Softmax
    min_temperature: 0.1     # Minimum temperature parameter for Gumbel Softmax
  noise:
    policy_noise: 0.2           # Standard deviation of noise
    noise_clip: 0.2             # Clipping value for noise 
    noise_std: 0.1         # Clipping value for noise
  dataset:
    training_file: "/rds/user/gtj21/hpc-work/designing-new-molecules/data/new_data/reactants_train.pkl"
    validation_file: "/rds/user/gtj21/hpc-work/designing-new-molecules/data/new_data/reactants_val.pkl"
    templates_file: "/rds/user/gtj21/hpc-work/designing-new-molecules/data/new_data/templates.pkl"